## https://bun.sh/guides/ecosystem/docker 

# Base image
FROM oven/bun:1 AS base
WORKDIR /usr/src/app

# Stage 1: Install dependencies
FROM base AS deps
COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile

# Install npm compatibility layer. TODO: try commenting this out and doing `bun add @next/swc-linux-arm64-gnu`
RUN bun add npm

# Next.js collects completely anonymous telemetry data about general usage: https://nextjs.org/telemetry
ENV NEXT_TELEMETRY_DISABLED 1

# Stage 2: Development stage
FROM base AS dev
WORKDIR /usr/src/app
COPY --from=deps /usr/src/app/node_modules ./node_modules
COPY . .

# Stage 3: Build the application
FROM base AS build
WORKDIR /usr/src/app
COPY --from=deps /usr/src/app/node_modules ./node_modules
COPY . .

# Enable output file tracing to reduce image size: https://nextjs.org/docs/advanced-features/output-file-tracing
ENV NEXT_OUTPUT_TRACE true
RUN bun next build

# Stage 4: Prepare production dependencies
FROM base AS prod-deps
WORKDIR /usr/src/app
COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile --production

# Stage 5: Final image for production
FROM base AS final
WORKDIR /usr/src/app

# Create a non-root user and group
RUN addgroup --system --gid 1001 nextjs
RUN adduser --system --uid 1001 nextjs

# Copy necessary files and set permissions
COPY --from=prod-deps /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/.next/standalone ./
COPY --from=build /usr/src/app/.next/static ./.next/static
COPY --from=build /usr/src/app/public ./public

# Change ownership to the non-root user
RUN chown -R nextjs:nextjs /usr/src/app

USER nextjs

EXPOSE 3000
CMD ["node", "server.js"]

# TODO:
# Flush all existing rules (optional, to start fresh)
# sudo iptables -F OUTPUT

# # Allow outgoing traffic on the approved port (e.g., 443 for HTTPS)
# sudo iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT

# # Allow outgoing traffic to localhost (loopback)
# sudo iptables -A OUTPUT -o lo -j ACCEPT

# # Block all other outgoing traffic
# sudo iptables -A OUTPUT -j DROP