services:
  frontend:
    build:
      context: ../frontend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "4000:4000"
