services:
  frontend:
    environment:
      - NODE_ENV=production
    command: ['bun', 'run', 'start']
    restart: always
    # deploy:
    #   replicas: 3

  backend:
    environment:
      - NODE_ENV=production
    command: ['bun', 'run', 'start']
    restart: always
    # deploy:
    #   replicas: 3

  postgres:
    environment:
      POSTGRES_USER: 'prod' # TODO: Change this
      POSTGRES_PASSWORD: 'prod'
      POSTGRES_DB: 'prod'
