# https://bun.sh/guides/ecosystem/docker
# Base image

FROM oven/bun:1 AS base
WORKDIR /usr/src/app

# Stage 1: Install development dependencies and cache them
FROM base AS deps
COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile

# Stage 2: Build the application (if needed)
FROM base AS build
COPY --from=deps /usr/src/app/node_modules ./node_modules
COPY . .
# Uncomment the following line if your backend requires a build step
# RUN bun run build

# Stage 3: Install production dependencies
FROM base AS prod-deps
COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile --production

# Stage 4: Final image
FROM base AS final
ENV NODE_ENV=production
USER bun
COPY --from=prod-deps /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app ./
EXPOSE 4000
CMD ["bun", "run", "start"]
