services:
  frontend:
    environment:
      NODE_ENV: production
    command: ['bun', 'run', 'start']
    restart: always
    # deploy:
    #   replicas: 3

  backend:
    environment:
      NODE_ENV: production
      POSTGRES_USER: prod
      POSTGRES_PASSWORD: prodpass
      POSTGRES_DB: prod_db
    command: ['bun', 'run', 'start']
    restart: always
    # deploy:
    #   replicas: 3

  postgres:
    environment:
      POSTGRES_USER: prod # TODO: Change this
      POSTGRES_PASSWORD: prodpass
      POSTGRES_DB: prod_db
